spring:
  application:
    name: product-microservice

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: jdbc:postgresql://postgres-product-microservice:5432/product-microservice-db
    username: postgres
    password: postgres

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh_expiration: ${JWT_REFRESH_EXPIRATION}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

server:
  port: 0

mq:
  queues:
    update-stock: update-stock
    update-stock-dlq: update-stock.dlq

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
