services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    networks:
      - ecommerce-api-network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  eurekaserver:
    build:
      context: ./eurekaserver
    image: eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - ecommerce-api-network

  clients:
    build:
      context: ./auth-microservice
    image: auth-microservice
    container_name: auth-microservice
    depends_on:
      - postgres-auth-microservice
    env_file: ./auth-microservice/.env
    networks:
      - ecommerce-api-network

  postgres-auth-microservice:
    image: postgres:16
    container_name: postgres-auth-microservice
    env_file: ./auth-microservice/.env
    networks:
      - ecommerce-api-network

  cloud-gateway:
    build:
      context: ./cloud-gateway
    image: cloud-gateway
    container_name: cloud-gateway
    ports:
      - "8080:8080"
    networks:
      - ecommerce-api-network

networks:
  ecommerce-api-network:
    driver: bridge
  
volumes:
  rabbitmq_data: