services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    networks:
      - ecommerce-api-network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  eurekaserver:
    build:
      context: ./eurekaserver
    image: eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - ecommerce-api-network

  auth-microservice:
    build:
      context: ./auth-microservice
    image: auth-microservice
    container_name: auth-microservice
    depends_on:
      - postgres-auth-microservice
    env_file: ./auth-microservice/.env
    volumes:
      - ./auth-microservice:/app
      
    command: ["./mvnw", "spring-boot:run"]
    # command: ./mvnw spring-boot:run
    networks:
      - ecommerce-api-network

  postgres-auth-microservice:
    image: postgres:16
    container_name: postgres-auth-microservice
    env_file: ./auth-microservice/.env
    networks:
      - ecommerce-api-network
    volumes:
      - auth_microservice_db:/var/lib/postgresql/data


  product-microservice:
    build:
      context: ./product-microservice
    image: product-microservice
    container_name: product-microservice
    depends_on:
      - postgres-product-microservice
    env_file: ./product-microservice/.env
    volumes:
      - ./product-microservice:/app
      
    command: ["./mvnw", "spring-boot:run"]
    networks:
      - ecommerce-api-network
  
  postgres-product-microservice:
    image: postgres:16
    container_name: postgres-product-microservice
    env_file: ./product-microservice/.env
    networks:
      - ecommerce-api-network
    volumes:
      - product_microservice_db:/var/lib/postgresql/data

  cloud-gateway:
    build:
      context: ./cloud-gateway
    image: cloud-gateway
    container_name: cloud-gateway
    env_file: ./cloud-gateway/.env
    ports:
      - "8080:8080"
    networks:
      - ecommerce-api-network

networks:
  ecommerce-api-network:
    driver: bridge
  
volumes:
  rabbitmq_data:
  auth_microservice_db:
  product_microservice_db: