services:
  auth-microservice:
    build:
      context: ./
    image: auth-microservice
    container_name: auth-microservice
    depends_on:
      - postgres-auth-microservice
    env_file: .env
    networks:
      - ecommerce-api-network

  postgres-auth-microservice:
    image: postgres:16
    container_name: postgres-auth-microservice
    env_file: .env
    networks:
      - ecommerce-api-network

networks:
  ecommerce-api-network:
    driver: bridge